name: Build Vaultwarden Multi-Arch Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPO: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get Vaultwarden Latest Release Version
        id: get_latest_version
        run: |
          LATEST_RELEASE_INFO=$(curl -sL "https://api.github.com/repos/dani-garcia/vaultwarden/releases/latest")
          VERSION=$(echo "$LATEST_RELEASE_INFO" | jq -r '.tag_name')

          echo "从 GitHub API 提取到的最新发布版本号 (用于 Docker 标签): $VERSION"

          if [ -z "$VERSION" ] || [ "$VERSION" = "null" ]; then
            echo "错误：无法从 GitHub API 获取到 Vaultwarden 的最新发布版本号。构建将立即终止。"
            echo "API 响应: $LATEST_RELEASE_INFO"
            exit 1
          fi

          echo "VAULTWARDEN_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Push Multi-Arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ env.VAULTWARDEN_VERSION }}
          #  ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:${{ env.VAULTWARDEN_VERSION }}-${{ secrets.DOCKER_USERNAME }}
          # --- 新增：将 VW_VERSION 作为 build-arg 传递给 Dockerfile ---
          build-args: |
            VW_VERSION=${{ env.VAULTWARDEN_VERSION }}
